export const PERMISSIONS = {
  // Kullanıcı Yönetimi
  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_MANAGE_ROLES: 'user.manage_roles',

  // Otel Yönetimi
  HOTEL_VIEW: 'hotel.view',
  HOTEL_CREATE: 'hotel.create',
  HOTEL_UPDATE: 'hotel.update',
  HOTEL_DELETE: 'hotel.delete',
  HOTEL_MANAGE_IMAGES: 'hotel.manage_images',
  HOTEL_MANAGE_ROOMS: 'hotel.manage_rooms',
  HOTEL_MANAGE_PRICES: 'hotel.manage_prices',
  HOTEL_MANAGE_INVENTORY: 'hotel.manage_inventory',

  // Rezervasyon Yönetimi
  RESERVATION_VIEW: 'reservation.view',
  RESERVATION_CREATE: 'reservation.create',
  RESERVATION_UPDATE: 'reservation.update',
  RESERVATION_DELETE: 'reservation.delete',
  RESERVATION_CANCEL: 'reservation.cancel',
  RESERVATION_CONFIRM: 'reservation.confirm',

  // Finansal İşlemler
  PAYMENT_VIEW: 'payment.view',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_UPDATE: 'payment.update',
  PAYMENT_REFUND: 'payment.refund',
  FINANCIAL_REPORTS: 'financial.reports',

  // Sistem Yönetimi
  SYSTEM_SETTINGS: 'system.settings',
  SYSTEM_LOGS: 'system.logs',
  SYSTEM_BACKUP: 'system.backup',

  // Raporlar
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  REPORTS_ADVANCED: 'reports.advanced',
} as const;

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  
  ADMIN: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.HOTEL_VIEW,
    PERMISSIONS.HOTEL_CREATE,
    PERMISSIONS.HOTEL_UPDATE,
    PERMISSIONS.HOTEL_MANAGE_IMAGES,
    PERMISSIONS.HOTEL_MANAGE_ROOMS,
    PERMISSIONS.HOTEL_MANAGE_PRICES,
    PERMISSIONS.HOTEL_MANAGE_INVENTORY,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_UPDATE,
    PERMISSIONS.RESERVATION_CANCEL,
    PERMISSIONS.RESERVATION_CONFIRM,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  MANAGER: [
    PERMISSIONS.HOTEL_VIEW,
    PERMISSIONS.HOTEL_UPDATE,
    PERMISSIONS.HOTEL_MANAGE_IMAGES,
    PERMISSIONS.HOTEL_MANAGE_ROOMS,
    PERMISSIONS.HOTEL_MANAGE_PRICES,
    PERMISSIONS.HOTEL_MANAGE_INVENTORY,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_UPDATE,
    PERMISSIONS.RESERVATION_CONFIRM,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  AGENT: [
    PERMISSIONS.HOTEL_VIEW,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_UPDATE,
    PERMISSIONS.PAYMENT_VIEW,
  ],

  CUSTOMER: [
    PERMISSIONS.HOTEL_VIEW,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
  ],
}; 